name: call_state_handler
description: "A Flutter plugin that detects phone calls and video calls on both Android and iOS platforms. This plugin helps you monitor call states in your app, allowing you to take appropriate actions when calls start or end."
version: 1.0.1
homepage: https://github.com/Abdusamad98/call_state_handler
repository: https://github.com/Abdusamad98/call_state_handler
issue_tracker: https://github.com/Abdusamad98/call_state_handler

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.call_state_handler
        pluginClass: CallDetectorPlugin
      ios:
        pluginClass: CallDetectorPlugin




