name: call_state_handler
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Abdusamad98/call_state_handler
repository: https://github.com/Abdusamad98/call_state_handler
issue_tracker: https://github.com/Abdusamad98/call_state_handler

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.call_detector
        pluginClass: CallDetectorPlugin
      ios:
        pluginClass: CallDetectorPlugin




